outputFilename: 
outputDirectory: target/proto
includeMessageDocs: true
includeFieldDocs: true
includeSourceLocationInDoc: true
inheritanceToComposition: false
includeValidationRules: false
customImports:
  - google/protobuf/timestamp.proto
  - google/protobuf/duration.proto
customImportLocations:
  - target/proto_deps
ignoreOutputFields:
  - uk.org.siri.www.siri/ServiceDeliveryStructure/DataObjectDelivery
  - uk.org.siri.www.siri/ServiceDeliveryBodyStructure/DataObjectDelivery
  - uk.org.siri.www.siri/SubscriptionRequestStructure/DataObjectSubscriptionRequest
  - uk.org.siri.www.siri/CapabilitiesResponseStructure/DataObjectCapabilitiesResponse
  - uk.org.siri.www.siri/ServiceRequestType/DataObjectRequest
  - uk.org.siri.www.siri/SubscriptionRequestType/DataObjectSubscriptionRequest
  - uk.org.siri.www.siri/ServiceDeliveryType/DataObjectDelivery
customTypeMappings:
  ^duration$ : google.protobuf.Duration
  ^dateTime$ : google.protobuf.Timestamp
  ^Entity_EntityStructure$ : EntityES
  ^Assignment_VersionStructure_$ : AssignmentVS
  ^ParkingEntranceForVehicles__VersionStructure: ParkingEntranceForVehicles
  ^GroupOfEntitiesRefStructure_$ : GroupOfEntitiesReference
  ^SeriesConstraintRefStructure_$ : SeriesConstraintReference
  ^PointOnLinkRefStructure_$ : PointOnLinkReference
  ^LineInDirectionRef_Structure$ : LineInDirectionReference
  ^OnboardStay_VersionedChlldStructure$: OnboardStay
  ^Site_VersionFrameStructure$ : SiteFrame
  ^VehicleType_VersionStructure_$ : VehicleTypeVSU
  ^VehicleType_VersionStructure$ : VehicleTypeVS
  ^(.*)Enumeration : $1

customNameMappings:
  ^Descriptor$ : TopographicPlaceDescriptor
  ^Assignment_VersionStructure_$ : AssignmentVS
  ^ParkingEntranceForVehicles__VersionStructure: ParkingEntranceForVehicles
  ^GroupOfEntitiesRefStructure_$ : GroupOfEntitiesReference
  ^SeriesConstraintRefStructure_$ : SeriesConstraintReference
  ^PointOnLinkRefStructure_$ : PointOnLinkReference
  ^LineInDirectionRef_Structure$ : LineInDirectionReference
  ^OnboardStay_VersionedChlldStructure$: OnboardStay
  ^Site_VersionFrameStructure$ : SiteFrame
  ^VehicleType_VersionStructure_$ : VehicleTypeVSU
  ^VehicleType_VersionStructure$ : VehicleTypeVS
  ^(.*)Enumeration : $1

options:
  java_multiple_files: true
