outputFilename: 
outputDirectory: target/proto
includeMessageDocs: true
includeFieldDocs: true
includeSourceLocationInDoc: true
inheritanceToComposition: false
includeValidationRules: true
customImports:
  - google/protobuf/timestamp.proto
  - google/protobuf/duration.proto
customImportLocations:
  - target/proto_deps
ignoreOutputFields:
  - uk.org.siri.www.siri/ServiceDeliveryStructure/DataObjectDelivery
  - uk.org.siri.www.siri/ServiceDeliveryBodyStructure/DataObjectDelivery
  - uk.org.siri.www.siri/SubscriptionRequestStructure/DataObjectSubscriptionRequest
  - uk.org.siri.www.siri/CapabilitiesResponseStructure/DataObjectCapabilitiesResponse
  - uk.org.siri.www.siri/ServiceRequestType/DataObjectRequest
  - uk.org.siri.www.siri/SubscriptionRequestType/DataObjectSubscriptionRequest
  - uk.org.siri.www.siri/ServiceDeliveryType/DataObjectDelivery
customTypeMappings:
  ^duration$ : google.protobuf.Duration
  ^dateTime$ : google.protobuf.Timestamp

customNameMappings:
  ^Descriptor$ : TopographicPlaceDescriptor

options:
  java_multiple_files: true
