version: 2.1
aliases:

- &release
  name: Release
  command: |
    if [ "$(git log -n 1 --pretty="%an")" == "renovate[bot]" ]
    then
      echo "Skipping release"
    else
    echo "Start release"
    git config --global user.email "circleci@entur.no"
    git config --global user.name "circleci"
    git checkout master
    git pull --no-edit
    git checkout develop
    mvn gitflow:release-start gitflow:release-finish -Prelease -DpostReleaseGoals=deploy -DargLine=-Prelease,'!protoc' -B
    git checkout master
    git pull --no-edit
    mvn deploy -DskipTests -Pentur-partner -P'!protoc'
    fi

- &import_gpg_key
  name: Configure GPG private key for signing project artifacts in OSS Sonatype
  command: |
    echo $SONATYPE_GPG_KEY_BASE64 | base64 --decode | gpg --batch --no-tty --import --yes

- &maven-settings-file
    "\"<settings xsi:schemaLocation='http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd' xmlns='http://maven.apache.org/SETTINGS/1.1.0'
            xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>
          <servers>
          <!-- Comment -->
            <server>
              <username>$SONATYPE_USERNAME</username>
              <password>$SONATYPE_PASSWORD</password>
              <id>ossrh</id>
            </server>
            <server>
              <username>$ARTIFACTORY_USER</username>
              <password>$ARTIFACTORY_PASSWORD</password>
              <id>entur-releases</id>
            </server>
            <server>
              <username>$ARTIFACTORY_USER</username>
              <password>$ARTIFACTORY_PASSWORD</password>
              <id>entur-snapshots</id>
            </server>
          </servers>
          <profiles>
      <profile>
        <repositories>
          <repository>
            <snapshots>
              <enabled>false</enabled>
            </snapshots>
            <id>entur-releases</id>
            <url>https://entur2.jfrog.io/entur2/partner-release</url>
          </repository>
          <repository>
            <snapshots />
            <id>entur-snapshots</id>
            <url>https://entur2.jfrog.io/entur2/partner-snapshot</url>
          </repository>
        </repositories>
        <pluginRepositories>
          <pluginRepository>
            <snapshots>
              <enabled>false</enabled>
            </snapshots>
            <id>entur-releases</id>
            <url>https://entur2.jfrog.io/entur2/partner-release</url>
          </pluginRepository>
          <pluginRepository>
            <snapshots />
            <id>entur-snapshots</id>
            <url>https://entur2.jfrog.io/entur2/partner-snapshot</url>
          </pluginRepository>
        </pluginRepositories>
        <properties>
          <entur_artifactory_partner_publish_snapshot_server_id>entur-snapshots</entur_artifactory_partner_publish_snapshot_server_id>
          <entur_artifactory_partner_publish_release_server_id>entur-releases</entur_artifactory_partner_publish_release_server_id>
          <entur_artifactory_partner_publish_snapshot_url>https://entur2.jfrog.io/entur2/partner-snapshot-local</entur_artifactory_partner_publish_snapshot_url>
          <entur_artifactory_partner_publish_release_url>https://entur2.jfrog.io/entur2/partner-release-local</entur_artifactory_partner_publish_release_url>
        </properties>
        <id>entur-partner</id>
      </profile>
    </profiles>
    <activeProfiles>
        <activeProfile>entur-partner</activeProfile>
    </activeProfiles>
    </settings>\""

- &java-container-config
  docker:
  - image: cimg/openjdk:18.0.2
    auth:
      username: $DOCKERHUB_LOGIN
      password: $DOCKERHUB_PASSWORD

commands:
  generate-maven-settings-file:
    parameters:
      settings-file:
        type: string
    steps:
    - run:
        name: Generate Maven Settings File
        command: |
          mkdir -p ~/.m2
          echo -e << parameters.settings-file >> > ~/.m2/settings.xml

jobs:
  test:
    <<: *java-container-config
    environment:
      MAVEN_OPTS: -Xmx3G -Xms1G
    steps:
    - checkout
    - generate-maven-settings-file:
        settings-file: *maven-settings-file
    - restore_cache:
        keys:
        - cache-dependencies-m2
    # Cannot use -o because of snapshot dependencies.
    - run: mvn deploy
    - save_cache:
        paths:
        - ~/.m2
        key: cache-dependencies-m2
    - run:
        name: Save test results
        command: |
          mkdir -p ~/junit/
          find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
        when: always
    - store_test_results:
        path: ~/junit
    - store_artifacts:
        path: ~/junit
    - run: *import_gpg_key
    - run: *release

orbs:
  queue: eddiewebb/queue@1.8.4

workflows:
  version: 2
  build_test_deploy:
    jobs:
    - queue/block_workflow:
        only-on-branch: develop
        time: '30'
        circleci-api-key: CIRCLE_API_USER_TOKEN
        context: global
    - test:
        context: global
        requires:
        - queue/block_workflow
        filters:
          branches:
            only: develop

