version: 2.1
aliases:
  - &downstream_builds
    name: Trigger downstream builds
    command: |
      echo 'export CIRCLE_API_TOKEN="$CIRCLE_API_USER_TOKEN"' >> $BASH_ENV
      /tools/downstream_single_trigger.sh "gh/entur/abt-protobuf" "develop"

  - &release
    name: Release
    command: |
        echo "Start release"
        git config --global user.email "circleci@entur.no"
        git config --global user.name "circleci"
        git checkout master
        git pull --no-edit
        git checkout develop
        mvn versions:use-releases
        mvn gitflow:release-start gitflow:release-finish -Prelease -DpostReleaseGoals=deploy -DargLine=-Prelease,'!protoc' -B

  - &import_gpg_key
    name: Configure GPG private key for signing project artifacts in OSS Sonatype
    command: |
      echo $SONATYPE_GPG_KEY_BASE64 | base64 --decode | gpg --batch --no-tty --import --yes


  - &maven-settings-file
      "\"<settings xsi:schemaLocation='http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd' xmlns='http://maven.apache.org/SETTINGS/1.1.0'
              xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>
            <servers>
            <server>
                   <username>$SONATYPE_USERNAME</username>
                   <password>$SONATYPE_PASSWORD</password>
                   <id>ossrh</id>
                 </server>
              <server>
                <username>$ARTIFACTORY_USER</username>
                <password>$ARTIFACTORY_PASSWORD</password>
                <id>central</id>
              </server>
              <server>
                <username>$ARTIFACTORY_USER</username>
                <password>$ARTIFACTORY_PASSWORD</password>
                <id>snapshots</id>
              </server>
            </servers>
            <profiles>
        <profile>
          <repositories>
            <repository>
              <snapshots>
                <enabled>false</enabled>
              </snapshots>
              <id>central</id>
              <name>entur-team-kontobasert-billettering-release</name>
              <url>https://entur2.jfrog.io/entur2/entur-team-kontobasert-billettering-release</url>
            </repository>
            <repository>
              <snapshots />
              <id>snapshots</id>
              <name>entur-team-kontobasert-billettering-snapshot</name>
              <url>https://entur2.jfrog.io/entur2/entur-team-kontobasert-billettering-snapshot</url>
            </repository>
          </repositories>
          <pluginRepositories>
            <pluginRepository>
              <snapshots>
                <enabled>false</enabled>
              </snapshots>
              <id>central</id>
              <name>entur-team-kontobasert-billettering-release</name>
              <url>https://entur2.jfrog.io/entur2/entur-team-kontobasert-billettering-release</url>
            </pluginRepository>
            <pluginRepository>
              <snapshots />
              <id>snapshots</id>
              <name>entur-team-kontobasert-billettering-snapshot</name>
              <url>https://entur2.jfrog.io/entur2/entur-team-kontobasert-billettering-snapshot</url>
            </pluginRepository>
          </pluginRepositories>
          <id>artifactory</id>
        </profile>
            </profiles>
            <activeProfiles>
              <activeProfile>artifactory</activeProfile>
            </activeProfiles>
          </settings>\""


  - &circleci-container-config
      docker:
        - image: eu.gcr.io/entur-system-1287/circleci-toolbox-image
          auth:
            username: _json_key
            password: $DOCKER_PASSWORD

  - &java-container-config
    docker:
      - image: circleci/openjdk:8-jdk

commands:
  generate-maven-settings-file:
    parameters:
      settings-file:
        type: string
    steps:
      - run:
          name: Generate Maven Settings File
          command: |
            mkdir -p ~/.m2
            echo -e << parameters.settings-file >> > ~/.m2/settings.xml

jobs:
  test:
    <<: *java-container-config
    environment:
      MAVEN_OPTS: -Xmx1G -Xms128m
    steps:
      - checkout
      - generate-maven-settings-file:
          settings-file: *maven-settings-file
      - restore_cache:
          keys:
            - cache-dependencies-m2
            - cache-dependencies-{{ checksum "pom.xml" }}
      - run: mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies
      # Cannot use -o because of snapshot dependencies.
      - run: mvn deploy -P '!protoc'
      - save_cache:
          paths:
            - ~/.m2
          key: cache-dependencies-{{ checksum "pom.xml" }}
      - save_cache:
          paths:
            - ~/.m2
          key: cache-dependencies-m2
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
  release:
    <<: *java-container-config
    environment:
      MAVEN_OPTS: -Xmx1G -Xms128m
    steps:
      - checkout
      - run: *import_gpg_key
      - generate-maven-settings-file:
          settings-file: *maven-settings-file
      - restore_cache:
          keys:
            - cache-dependencies-m2
            - cache-dependencies-{{ checksum "pom.xml" }}
      - run: *release

  postBuild:
    <<: *circleci-container-config

    steps:
      - run: *downstream_builds

orbs:
  queue: eddiewebb/queue@volatile

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - queue/block_workflow:
          only-on-branch: develop
          time: '30'
          circleci-api-key: CIRCLE_API_USER_TOKEN
          context: global
      - test:
          context: global
          requires:
            - queue/block_workflow
      - postBuild:
          context: global
          requires:
            - release
          filters:
            branches:
              only: develop
      - release:
          context: global
          requires:
            - test
          filters:
            branches:
              only: develop
